
services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`finke.oesterlin.dev`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    restart: always
    networks:
      - traefik_web
    

networks:
  traefik_web:
    external: true